# Generated by Django 3.0.3 on 2020-02-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CER', 'cerveja'), ('REF', 'refrigerante'), ('SUC', 'suco')], max_length=3)),
                ('estoque_inicial', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0)),
            ],
        ),
    ]
